service: demo-lambda-error-handling-logging

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  stage: ${opt:stage, "dev"}
  logRetentionInDays: 3
  memorySize: 128
  timeout: 6
  logs:
    httpApi: true
  environment:
    LOG_LEVEL: DEBUG

functions:
  calc:
    handler: functions/calc.handler
    events:
      - httpApi:
          path: /calc
          method: post
